// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var app, cheerio, express, fs, request;

  express = require('express');

  fs = require('fs');

  request = require('request');

  cheerio = require('cheerio');

  app = express();

  app.get('/scrape', function(req, res) {
    var url;
    url = 'http://www.imdb.com/title/tt1229340/';
    return request(url, function(err, response, html) {
      var $, json;
      if (!err) {
        $ = cheerio.load(html);
        json = {
          title: "",
          release: "",
          rating: ""
        };
        $('.header').filter(function() {
          var data, release, title;
          data = $(this);
          title = data.children().first().text();
          release = data.children().last().children().text();
          json.title = title;
          json.release = release;
        });
        $('.star-box-giga-star').filter(function() {
          var data, rating;
          data = $(this);
          rating = data.text();
          json.rating = rating;
        });
      }
      fs.writeFile('output.json', JSON.stringify(json, null, 4), function(err) {
        console.log('File successfully written!');
      });
      res.send('check your console!!');
    });
  }).listen('9009', function() {
    console.log('Server was running at port 9009');
  });

}).call(this);
